fn main() {
    let manifest = tauri_build::AppManifest::new().commands(&[
        "runtime_status",
        "runtime_provision",
        "runtime_start",
        "runtime_stop",
        "runtime_verify",
        "runtime_repair",
        "runtime_logs",
    ]);
    let attributes = tauri_build::Attributes::new().app_manifest(manifest);
    tauri_build::try_build(attributes).expect("failed to build RHODIZ Harness Desktop ACL");
    normalize_generated_permissions();
}

/// Rewrites the ACL files tauri_build just generated so their line endings are
/// LF on every platform.
///
/// These files are committed: they are the audited record of which commands the
/// renderer may call, so a reviewer reads them in the diff. tauri_build writes
/// them with the host's native endings, which on Windows means every build
/// leaves all seven reported as modified by `git status` — a dirty tree with no
/// content change, on every compile, which is exactly the kind of noise that
/// teaches people to stop reading `git status` before they commit.
///
/// `.gitattributes` pins these paths to LF, which fixes what a checkout writes
/// but not what this build script writes; `git status` still compares the bytes
/// on disk. Both halves are needed, so this is the other half.
fn normalize_generated_permissions() {
    let dir = std::path::Path::new("permissions/autogenerated");
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "toml") {
            if let Ok(text) = std::fs::read_to_string(&path) {
                if text.contains("\r\n") {
                    let _ = std::fs::write(&path, text.replace("\r\n", "\n"));
                }
            }
        }
    }
}
