// Compiles the vendored onyx design tokens into CSS custom properties.
//
// Upstream builds these with Style Dictionary v4. This does the same job in
// forty lines because the desktop app needs one output — CSS variables — and
// not the five that upstream emits for its web and React Native consumers.
// The trade is deliberate: a build-time dependency tree is supply-chain
// surface in an application that ships signed releases, and `src/design/
// tokens/*.json` stays byte-identical to upstream either way, so switching
// back to Style Dictionary later is a script change and not a data migration.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const dir = fileURLToPath(new URL('../src/design/tokens/', import.meta.url))
const load = (name) => JSON.parse(readFileSync(dir + name, 'utf8'))

/** Flattens `{a:{b:{value}}}` into `{'a-b': value}`, upstream's own shape. */
function flatten(node, prefix = '', out = {}) {
  for (const [key, value] of Object.entries(node)) {
    if (value && typeof value === 'object' && 'value' in value) {
      out[prefix ? `${prefix}-${key}` : key] = value.value
    } else if (value && typeof value === 'object') {
      flatten(value, prefix ? `${prefix}-${key}` : key, out)
    }
  }
  return out
}

/** Same walk, but keeps each leaf's declared `type` so colours can be told
 *  apart from sizes when building the Tailwind theme. */
function flattenTypes(node, prefix = '', out = {}) {
  for (const [key, value] of Object.entries(node)) {
    if (value && typeof value === 'object' && 'value' in value) {
      out[prefix ? `${prefix}-${key}` : key] = value.type
    } else if (value && typeof value === 'object') {
      flattenTypes(value, prefix ? `${prefix}-${key}` : key, out)
    }
  }
  return out
}

const primitives = flatten(load('primitives.json'))

/** Resolves `{alias}` against the primitives. Upstream allows one hop. */
function resolve(value, seen = new Set()) {
  if (typeof value !== 'string') return value
  const match = /^\{([^}]+)\}$/.exec(value.trim())
  if (!match) return value
  const name = match[1].replaceAll('.', '-')
  if (seen.has(name)) throw new Error(`token alias cycle at {${name}}`)
  if (!(name in primitives)) throw new Error(`token alias {${name}} has no primitive`)
  return resolve(primitives[name], seen.add(name))
}

const emit = (pairs, indent = '  ') =>
  Object.entries(pairs)
    .map(([k, v]) => `${indent}--${k}: ${resolve(v)};`)
    .join('\n')

const dark = flatten(load('semantic-dark.json'))
const light = flatten(load('semantic-light.json'))
const size = flatten(load('size.json'))
const shadow = flatten(load('shadow.json'))

// Upstream nests the semantic sets under a `dark` / `light` key. Strip it so a
// component names the role (`--text-04`) and never the theme it came from.
const strip = (pairs, lead) =>
  Object.fromEntries(
    Object.entries(pairs).map(([k, v]) => [k.startsWith(lead + '-') ? k.slice(lead.length + 1) : k, v]),
  )

// Dark is the default because this is a desktop tool that sits open all day
// next to a terminal, not a document surface. Light is opt-in under `.light`
// rather than dropped, so the pair upstream ships stays a pair here.
const css = `/* GENERATED by scripts/build-tokens.mjs — do not edit.
 * Source: src/design/tokens/*.json, vendored unmodified from onyx-foss.
 * See PROVENANCE.md. Regenerate with \`npm run build:tokens\`.
 */
:root {
${emit(primitives)}

${emit(size)}

${emit(shadow)}

${emit(strip(dark, 'dark'))}
}

.light {
${emit(strip(light, 'light'))}
}
`

writeFileSync(fileURLToPath(new URL('../src/design/tokens.css', import.meta.url)), css)

// Tailwind 4 theme, generated rather than hand-kept. The utility names mirror
// opal/tailwind-preset.cjs one-for-one (`bg-background-neutral-01`,
// `text-text-04`, `border-border-01`), so an Opal component adapted later
// needs no class rewriting — and so this file cannot drift from the tokens.
const darkTypes = strip(flattenTypes(load('semantic-dark.json')), 'dark')
const colorNames = Object.keys(strip(dark, 'dark'))
  .filter((name) => darkTypes[name] === 'color')
  .sort()
const theme = `/* GENERATED by scripts/build-tokens.mjs — do not edit. */
@theme inline {
${colorNames.map((n) => `  --color-${n}: var(--${n});`).join('\n')}
}
`
writeFileSync(fileURLToPath(new URL('../src/design/theme.css', import.meta.url)), theme)
console.log(`build-tokens: ${colorNames.length} colour utilities -> src/design/theme.css`)
const count = Object.keys(primitives).length + Object.keys(dark).length
console.log(`build-tokens: ${count} tokens -> src/design/tokens.css`)
